### ISSUE TITLE
Unable to locate 'C:\Users\<username>\.nuget\packages\Obfuscar.2.2.28\tools\Obfuscar.Console.exe'

### ISSUE THREAD

**Issue by hoangitk** [ennerperez/msbuild-obfuscar#5]
Hi,
There latest version got an error as below

"Unable to locate 'C:\Users\username\\.nuget\packages\\**Obfuscar.2.2.28**\tools\Obfuscar.Console.exe'"

Correct path should be: C:\Users\username\\.nuget\packages\\**Obfuscar\2.2.28**\tools\Obfuscar.Console.exe'

Thank you!

**Comment by warappa** [comment]
Hello @ennerperez ,
this fix is indeed required as now with `PackageReference` projects it's not working.
PR 4 (https://github.com/ennerperez/msbuild-obfuscar/pull/4) has the fix, but was not merged yet.

**Comment by ennerperez** [comment]
Changes accepted, next build will assume that.

**Comment by p-vogt** [comment]
Hi @ennerperez , first of all thank you for this helpful lib.

Unfortunately, it is not working in my azure pipeline (linux) since the path is wrong.
Why did you change the path in: https://github.com/ennerperez/msbuild-obfuscar/commit/e2913f928c4b044cff25fd04f50fc8be12500fff ?

`/home/vsts/.nuget/packages/msbuild.obfuscar/2.2.35.1/build/MSBuild.Obfuscar.targets(50,9): error : Unable to locate '/home/vsts/.nuget/packages/Obfuscar/2.2.35/tools/Obfuscar.Console.exe'`

I think it can't find the file because 'Obfuscar' needs to be 'obfuscar'.

**Comment by ennerperez** [comment]
Yes, I'll check this asap. Ty
